### ISSUE TITLE
wheres the ender 3 firmware?

### ISSUE THREAD

**Issue by Kevivally** [KarlTorp/MKS_CR10_mini#6]

**Comment by Kevivally** [comment]
owner is lazy

**Comment by KarlTorp** [comment]
@Kevivally Will upload when you have replaced the smoked MKS board on your ender 5 and learn to ensure that your supply is securely connected.

**Comment by Kevivally** [comment]
well do you have a mks board i can buy

**Comment by bogosii** [comment]
> @Kevivally Will upload when you have replaced the smoked MKS board on your ender 5 and learn to ensure that your supply is securely connected.

![image](https://user-images.githubusercontent.com/28623865/57013116-3d929480-6c0a-11e9-942a-95df43355af9.png)

**Comment by KarlTorp** [comment]
Sorry no spare. But make sure that the connectors for supply, bed and hot end are rated to the applied current and not cheep knock offs. And make sure that the wires does not have solder on the ends. And that the clamps are tight.

**Comment by Kevivally** [comment]
they had solder and that was why i think

**Comment by Kevivally** [comment]
du kan tro der kommer et issue på aliexpress

**Comment by KarlTorp** [comment]
Yep. It can melt under high load.

**Comment by KarlTorp** [comment]
@Kevivally the Ender3 repo has arrived

**Comment by Kevivally** [comment]
![Tuxedo Pooh 02052019083106](https://user-images.githubusercontent.com/32248970/57059261-c534dd80-6cb4-11e9-850f-5848c6ab6575.jpg)

**Comment by Kevivally** [comment]
ive seen your "firmware" and all the goodies are disabled.... shame

**Comment by Kevivally** [comment]
![2zybzr](https://user-images.githubusercontent.com/32248970/57059357-3f656200-6cb5-11e9-90d5-8669929db567.jpg)

**Comment by KarlTorp** [comment]
Never mind then. Have fun with your pretty horse ass

**Comment by Kevivally** [comment]
dont worry i will fix your firmware for you

**Comment by Kevivally** [comment]
if you would add me as collaber

**Comment by Kevivally** [comment]
https://www.precisionpiezo.co.uk/product-page/precision-piezo-orion-pcb
